from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from database import get_db
from models import User, ParametricProfile
from schemas import RegisterPayload, LoginPayload
from security import get_password_hash, verify_password, create_access_token

router = APIRouter(prefix="/api", tags=["auth"])

@router.post("/register")
def register_user(payload: RegisterPayload, db: Session = Depends(get_db)):
    # 1. Check if the phone number already exists in Postgres
    existing_user = db.query(User).filter(User.phone_number == payload.phone_number).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Phone number already registered")

    # 2. Hash the plaintext password sent from the phone
    hashed_pw = get_password_hash(payload.password)

    # 3. Save the User using the UUID generated by the frontend SQLite
    new_user = User(
        user_id=payload.local_user_id,
        phone_number=payload.phone_number,
        password_hash=hashed_pw
    )
    db.add(new_user)
    
    # 4. Save the Profile
    new_profile = ParametricProfile(
        profile_id=payload.local_profile_id,
        user_id=payload.local_user_id,
        name=payload.name,
        language_code=payload.language_code,
        occupation_type=payload.occupation_type,
        education_level=payload.education_level,
        income_type=payload.income_type,
        income_value=payload.income_value,
        current_balance=payload.current_balance,
        crop_type=payload.crop_type,
        land_holding=payload.land_holding,
        income_pattern=payload.income_pattern,
        is_blind=payload.is_blind
    )
    db.add(new_profile)
    db.commit()

    # 5. Generate and return the secure JWT
    access_token = create_access_token(data={"sub": new_user.user_id, "phone": new_user.phone_number})
    
    return {"access_token": access_token, "token_type": "bearer", "status": "success"}


@router.post("/login")
def login_user(payload: LoginPayload, db: Session = Depends(get_db)):
    # 1. Fetch user by phone number
    user = db.query(User).filter(User.phone_number == payload.phone_number).first()
    if not user:
        raise HTTPException(status_code=400, detail="Invalid phone number or password")

    # 2. Verify password hash
    if not verify_password(payload.password, user.password_hash):
        raise HTTPException(status_code=400, detail="Invalid phone number or password")

    # 3. Retrieve user profile
    profile = db.query(ParametricProfile).filter(ParametricProfile.user_id == user.user_id).first()

    # 4. Generate access token
    access_token = create_access_token(data={"sub": user.user_id, "phone": user.phone_number})

    # 5. Format profile details
    profile_data = None
    if profile:
        profile_data = {
            "profile_id": profile.profile_id,
            "user_id": profile.user_id,
            "name": profile.name,
            "language_code": profile.language_code,
            "occupation_type": profile.occupation_type,
            "education_level": profile.education_level,
            "income_type": profile.income_type,
            "income_value": profile.income_value,
            "current_balance": profile.current_balance,
            "crop_type": profile.crop_type,
            "land_holding": profile.land_holding,
            "income_pattern": profile.income_pattern,
            "is_blind": 1 if profile.is_blind else 0,
            "trust_score": profile.trust_score
        }

    return {
        "access_token": access_token,
        "token_type": "bearer",
        "user_id": user.user_id,
        "profile": profile_data,
        "status": "success"
    }


@router.get("/profiles")
def get_all_profiles(db: Session = Depends(get_db)):
    # Fetch all profiles from the PostgreSQL database
    profiles = db.query(ParametricProfile).all()
    return profiles
