# main.py
import os
import base64
import json
import requests
from dotenv import load_dotenv
from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy import text
from sqlalchemy.orm import Session
from pydantic import BaseModel
import bcrypt
from jose import jwt
from datetime import datetime, timedelta
from typing import Optional
from fastapi import UploadFile, File
from database import get_db, engine, Base
from models import User, ParametricProfile, Transaction

# Load environment variables
load_dotenv()

# Run automatic schema migration for PostgreSQL
try:
    # Auto create tables including the new transactions table
    Base.metadata.create_all(bind=engine)
    with engine.connect() as conn:
        conn.execute(text("ALTER TABLE parametric_profiles ADD COLUMN IF NOT EXISTS is_blind BOOLEAN DEFAULT FALSE;"))
        conn.commit()
    print("✅ PostgreSQL Schema Migration: Tables created & 'is_blind' column verified/added")
except Exception as e:
    print(f"⚠️ PostgreSQL Schema Migration Failed: {e}")

app = FastAPI(title="ArthaSaathi API")

# --- Security Configuration ---
# --- Security Configuration ---
SECRET_KEY = "artha-saathi-super-secret-key"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_DAYS = 30

def get_password_hash(password: str):
    # bcrypt requires encoding strings into bytes before hashing
    salt = bcrypt.gensalt()
    hashed_bytes = bcrypt.hashpw(password.encode('utf-8'), salt)
    return hashed_bytes.decode('utf-8') # Decode back to string for Postgres

def verify_password(plain_password: str, hashed_password: str):
    return bcrypt.checkpw(plain_password.encode('utf-8'), hashed_password.encode('utf-8'))

def create_access_token(data: dict):
    to_encode = data.copy()
    expire = datetime.utcnow() + timedelta(days=ACCESS_TOKEN_EXPIRE_DAYS)
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)

# --- Pydantic Schema (Matches Frontend Payload) ---
class RegisterPayload(BaseModel):
    local_user_id: str
    local_profile_id: str
    phone_number: str
    password: str
    name: str
    language_code: str
    occupation_type: str
    education_level: str
    income_type: str
    income_value: str
    current_balance: float
    crop_type: Optional[str] = None
    land_holding: Optional[str] = None
    income_pattern: Optional[str] = None
    is_blind: bool = False

class LoginPayload(BaseModel):
    phone_number: str
    password: str

class TransactionSyncItem(BaseModel):
    transaction_id: str
    amount: float
    type: str  # 'credit' or 'debit'
    reason: str
    created_at: str

class SyncPayload(BaseModel):
    user_id: str
    transactions: list[TransactionSyncItem]

# --- Registration Endpoint ---
@app.post("/api/register")
def register_user(payload: RegisterPayload, db: Session = Depends(get_db)):
    # 1. Check if the phone number already exists in Postgres
    existing_user = db.query(User).filter(User.phone_number == payload.phone_number).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Phone number already registered")

    # 2. Hash the plaintext password sent from the phone
    hashed_pw = get_password_hash(payload.password)

    # 3. Save the User using the UUID generated by the frontend SQLite
    new_user = User(
        user_id=payload.local_user_id,
        phone_number=payload.phone_number,
        password_hash=hashed_pw
    )
    db.add(new_user)

    
    
    # 4. Save the Profile
    new_profile = ParametricProfile(
        profile_id=payload.local_profile_id,
        user_id=payload.local_user_id,
        name=payload.name,
        language_code=payload.language_code,
        occupation_type=payload.occupation_type,
        education_level=payload.education_level,
        income_type=payload.income_type,
        income_value=payload.income_value,
        current_balance=payload.current_balance,
        crop_type=payload.crop_type,
        land_holding=payload.land_holding,
        income_pattern=payload.income_pattern,
        is_blind=payload.is_blind
    )
    db.add(new_profile)
    db.commit()

    # 5. Generate and return the secure JWT
    access_token = create_access_token(data={"sub": new_user.user_id, "phone": new_user.phone_number})
    
    return {"access_token": access_token, "token_type": "bearer", "status": "success"}


@app.post("/api/login")
def login_user(payload: LoginPayload, db: Session = Depends(get_db)):
    # 1. Fetch user by phone number
    user = db.query(User).filter(User.phone_number == payload.phone_number).first()
    if not user:
        raise HTTPException(status_code=400, detail="Invalid phone number or password")

    # 2. Verify password hash
    if not verify_password(payload.password, user.password_hash):
        raise HTTPException(status_code=400, detail="Invalid phone number or password")

    # 3. Retrieve user profile
    profile = db.query(ParametricProfile).filter(ParametricProfile.user_id == user.user_id).first()

    # 4. Generate access token
    access_token = create_access_token(data={"sub": user.user_id, "phone": user.phone_number})

    # 5. Format profile details
    profile_data = None
    if profile:
        profile_data = {
            "profile_id": profile.profile_id,
            "user_id": profile.user_id,
            "name": profile.name,
            "language_code": profile.language_code,
            "occupation_type": profile.occupation_type,
            "education_level": profile.education_level,
            "income_type": profile.income_type,
            "income_value": profile.income_value,
            "current_balance": profile.current_balance,
            "crop_type": profile.crop_type,
            "land_holding": profile.land_holding,
            "income_pattern": profile.income_pattern,
            "is_blind": 1 if profile.is_blind else 0,
            "trust_score": profile.trust_score
        }

    return {
        "access_token": access_token,
        "token_type": "bearer",
        "user_id": user.user_id,
        "profile": profile_data,
        "status": "success"
    }


@app.get("/api/profiles")
def get_all_profiles(db: Session = Depends(get_db)):
    # Fetch all profiles from the PostgreSQL database
    profiles = db.query(ParametricProfile).all()
    return profiles


@app.post("/api/transactions/sync")
def sync_transactions(payload: SyncPayload, db: Session = Depends(get_db)):
    # 1. Verify user exists
    user = db.query(User).filter(User.user_id == payload.user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
        
    profile = db.query(ParametricProfile).filter(ParametricProfile.user_id == payload.user_id).first()
    
    synced_ids = []
    
    for item in payload.transactions:
        # Check if transaction already exists in Postgres (idempotency check)
        existing = db.query(Transaction).filter(Transaction.transaction_id == item.transaction_id).first()
        if not existing:
            # Parse created_at string
            try:
                # Handle SQLite timestamp format 'YYYY-MM-DD HH:MM:SS' or ISO format
                date_str = item.created_at.replace('T', ' ').replace('Z', '')
                created_dt = datetime.strptime(date_str, "%Y-%m-%d %H:%M:%S")
            except Exception:
                created_dt = datetime.utcnow()
                
            new_tx = Transaction(
                transaction_id=item.transaction_id,
                user_id=payload.user_id,
                amount=item.amount,
                type=item.type,
                reason=item.reason,
                created_at=created_dt
            )
            db.add(new_tx)
            
            # Update current balance in PostgreSQL
            if profile:
                if item.type == 'credit':
                    profile.current_balance += item.amount
                else:
                    profile.current_balance -= item.amount
                    
        synced_ids.append(item.transaction_id)
        
    db.commit()
    return {"status": "success", "synced_ids": synced_ids}


@app.post("/audio-khata")
async def audio_khata(audio: UploadFile = File(...)):
    content = await audio.read()
    
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key or api_key == "YOUR_GEMINI_API_KEY_HERE":
        print("⚠️ Gemini API Key not configured or placeholder. Falling back to Mock response.")
        return {
            "amount": 150.0,
            "type": "debit",
            "reason": "Milk and Groceries (Mock)",
            "reply": "Gemini API key is not set. Showing mock response: Spent 150 rupees on Milk and Groceries.",
            "tts_language": "en",
            "status": "success"
        }
        
    try:
        # Base64 encode the audio file
        audio_b64 = base64.b64encode(content).decode("utf-8")
        
        # Determine the MIME type (Gemini rejects audio/mp4 for inline data, requires audio/m4a)
        mime_type = "audio/m4a"
        if audio.content_type and "wav" in audio.content_type:
            mime_type = "audio/wav"
        elif audio.content_type and "mp3" in audio.content_type:
            mime_type = "audio/mp3"
        
        # Build the payload
        payload = {
            "contents": [
                {
                    "parts": [
                        {
                            "inlineData": {
                                "mimeType": mime_type,
                                "data": audio_b64
                            }
                        },
                        {
                            "text": (
                                "You are a multilingual voice transaction analyzer for a financial app named 'ArthSaathi'. "
                                "The user has spoken a transaction in their local language (which could be English, Hindi, Marathi, Tamil, Telugu, Kannada, Bengali, Gujarati, etc.).\n\n"
                                "Analyze the audio and extract the transaction details:\n"
                                "1. Transcribe the spoken amount (numerical value only).\n"
                                "2. Classify the transaction type as 'debit' (for spending, paying, buying) or 'credit' (for earning, receiving, salary).\n"
                                "3. Transcribe or summarize the reason/item (e.g. 'vegetables', 'milk', 'bus fare', 'salary').\n"
                                "4. Formulate a short, natural confirmation 'reply' speaking in the EXACT same language that the user spoke (e.g., in Hindi: 'दूध के लिए 150 रुपये खर्च किए गए हैं', in Tamil: 'பாலுக்கு 150 ரூபாய் செலவு பதிவு செய்யப்பட்டது', in English: 'Recorded spent of 150 rupees on milk').\n"
                                "5. Identify the 2-letter ISO 639-1 language code of the language they spoke as 'tts_language' (e.g. 'hi' for Hindi, 'mr' for Marathi, 'ta' for Tamil, 'en' for English).\n\n"
                                "You MUST return your response as a raw JSON object strictly conforming to this schema:\n"
                                "{\n"
                                "  \"amount\": float,\n"
                                "  \"type\": \"debit\" | \"credit\",\n"
                                "  \"reason\": \"string\",\n"
                                "  \"reply\": \"string\",\n"
                                "  \"tts_language\": \"string\"\n"
                                "}"
                            )
                        }
                    ]
                }
            ],
            "generationConfig": {
                "responseMimeType": "application/json"
            }
        }
        
        # Call Gemini API
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"
        res = requests.post(url, json=payload, headers={"Content-Type": "application/json"}, timeout=15)
        
        if res.status_code != 200:
            raise HTTPException(
                status_code=res.status_code, 
                detail=f"Gemini API error: {res.text}"
            )
            
        res_json = res.json()
        
        # Extract the text part which contains the JSON string
        raw_text = res_json["candidates"][0]["content"]["parts"][0]["text"]
        result = json.loads(raw_text.strip())
        
        # Validate that the expected keys exist
        required_keys = ["amount", "type", "reason", "reply", "tts_language"]
        for key in required_keys:
            if key not in result:
                raise ValueError(f"Gemini response missing required key: {key}")
                
        result["status"] = "success"
        return result
        
    except Exception as e:
        print(f"❌ Error processing audio with Gemini: {e}")
        # Graceful fallback to avoid app crash
        return {
            "amount": 0.0,
            "type": "debit",
            "reason": "Error",
            "reply": f"Could not process voice recording. Error: {str(e)}",
            "tts_language": "en",
            "status": "error"
        }