# main.py
import os
import uuid
import pytesseract
import cv2
import numpy as np
from PIL import Image
import chromadb
from sentence_transformers import SentenceTransformer
from fastapi import FastAPI, Depends, HTTPException, UploadFile, File, Form
from sqlalchemy import text
from sqlalchemy.orm import Session
from pydantic import BaseModel
import bcrypt
from jose import jwt
from datetime import datetime, timedelta
from typing import Optional

from database import get_db, engine
from models import User, ParametricProfile, ChatSession, ChatMessage, Document

# Setup Tesseract path for Windows
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

# Setup Chroma DB
chroma_client = chromadb.PersistentClient(path="./chroma_data")
chat_collection = chroma_client.get_or_create_collection(name="chat_embeddings")

# Setup Sentence Transformer (loads all-MiniLM-L6-v2)
embedder = SentenceTransformer('all-MiniLM-L6-v2')

os.makedirs("uploads/images", exist_ok=True)

# Run automatic schema migration for PostgreSQL
try:
    with engine.connect() as conn:
        conn.execute(text("ALTER TABLE parametric_profiles ADD COLUMN IF NOT EXISTS is_blind BOOLEAN DEFAULT FALSE;"))
        conn.commit()
    print("✅ PostgreSQL Schema Migration: 'is_blind' column verified/added")
except Exception as e:
    print(f"⚠️ PostgreSQL Schema Migration Failed: {e}")

app = FastAPI(title="ArthaSaathi API")

# --- Security Configuration ---
# --- Security Configuration ---
SECRET_KEY = "artha-saathi-super-secret-key"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_DAYS = 30

def get_password_hash(password: str):
    # bcrypt requires encoding strings into bytes before hashing
    salt = bcrypt.gensalt()
    hashed_bytes = bcrypt.hashpw(password.encode('utf-8'), salt)
    return hashed_bytes.decode('utf-8') # Decode back to string for Postgres

def verify_password(plain_password: str, hashed_password: str):
    return bcrypt.checkpw(plain_password.encode('utf-8'), hashed_password.encode('utf-8'))

def create_access_token(data: dict):
    to_encode = data.copy()
    expire = datetime.utcnow() + timedelta(days=ACCESS_TOKEN_EXPIRE_DAYS)
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)

# --- Pydantic Schema (Matches Frontend Payload) ---
class RegisterPayload(BaseModel):
    local_user_id: str
    local_profile_id: str
    phone_number: str
    password: str
    name: str
    language_code: str
    occupation_type: str
    education_level: str
    income_type: str
    income_value: str
    current_balance: float
    crop_type: Optional[str] = None
    land_holding: Optional[str] = None
    income_pattern: Optional[str] = None
    is_blind: bool = False

class LoginPayload(BaseModel):
    phone_number: str
    password: str

# --- Registration Endpoint ---
@app.post("/api/register")
def register_user(payload: RegisterPayload, db: Session = Depends(get_db)):
    # 1. Check if the phone number already exists in Postgres
    existing_user = db.query(User).filter(User.phone_number == payload.phone_number).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Phone number already registered")

    # 2. Hash the plaintext password sent from the phone
    hashed_pw = get_password_hash(payload.password)

    # 3. Save the User using the UUID generated by the frontend SQLite
    new_user = User(
        user_id=payload.local_user_id,
        phone_number=payload.phone_number,
        password_hash=hashed_pw
    )
    db.add(new_user)
    
    # 4. Save the Profile
    new_profile = ParametricProfile(
        profile_id=payload.local_profile_id,
        user_id=payload.local_user_id,
        name=payload.name,
        language_code=payload.language_code,
        occupation_type=payload.occupation_type,
        education_level=payload.education_level,
        income_type=payload.income_type,
        income_value=payload.income_value,
        current_balance=payload.current_balance,
        crop_type=payload.crop_type,
        land_holding=payload.land_holding,
        income_pattern=payload.income_pattern,
        is_blind=payload.is_blind
    )
    db.add(new_profile)
    db.commit()

    # 5. Generate and return the secure JWT
    access_token = create_access_token(data={"sub": new_user.user_id, "phone": new_user.phone_number})
    
    return {"access_token": access_token, "token_type": "bearer", "status": "success"}


@app.post("/api/login")
def login_user(payload: LoginPayload, db: Session = Depends(get_db)):
    # 1. Fetch user by phone number
    user = db.query(User).filter(User.phone_number == payload.phone_number).first()
    if not user:
        raise HTTPException(status_code=400, detail="Invalid phone number or password")

    # 2. Verify password hash
    if not verify_password(payload.password, user.password_hash):
        raise HTTPException(status_code=400, detail="Invalid phone number or password")

    # 3. Retrieve user profile
    profile = db.query(ParametricProfile).filter(ParametricProfile.user_id == user.user_id).first()

    # 4. Generate access token
    access_token = create_access_token(data={"sub": user.user_id, "phone": user.phone_number})

    # 5. Format profile details
    profile_data = None
    if profile:
        profile_data = {
            "profile_id": profile.profile_id,
            "user_id": profile.user_id,
            "name": profile.name,
            "language_code": profile.language_code,
            "occupation_type": profile.occupation_type,
            "education_level": profile.education_level,
            "income_type": profile.income_type,
            "income_value": profile.income_value,
            "current_balance": profile.current_balance,
            "crop_type": profile.crop_type,
            "land_holding": profile.land_holding,
            "income_pattern": profile.income_pattern,
            "is_blind": 1 if profile.is_blind else 0,
            "trust_score": profile.trust_score
        }

    return {
        "access_token": access_token,
        "token_type": "bearer",
        "user_id": user.user_id,
        "profile": profile_data,
        "status": "success"
    }


@app.get("/api/profiles")
def get_all_profiles(db: Session = Depends(get_db)):
    # Fetch all profiles from the PostgreSQL database
    profiles = db.query(ParametricProfile).all()
    return profiles

@app.post("/api/chat/message")
async def chat_message(
    user_id: str = Form(...),
    session_title: str = Form("New Conversation"),
    message: str = Form(""),
    image: Optional[UploadFile] = File(None),
    db: Session = Depends(get_db)
):
    # 1. Handle Chat Session
    session = db.query(ChatSession).filter(ChatSession.user_id == user_id).order_by(ChatSession.created_at.desc()).first()
    if not session:
        session = ChatSession(user_id=user_id, session_title=session_title)
        db.add(session)
        db.commit()

    document_record = None
    ocr_text = ""

    # 2. Handle Image Upload & OCR
    if image:
        file_ext = image.filename.split('.')[-1] if '.' in image.filename else 'jpg'
        file_path = f"uploads/images/{uuid.uuid4()}.{file_ext}"
        
        with open(file_path, "wb") as buffer:
            buffer.write(await image.read())
            
        # Run OCR with OpenCV Preprocessing
        try:
            # Read image using OpenCV
            cv_img = cv2.imread(file_path)
            
            # 1. Convert to Grayscale
            gray = cv2.cvtColor(cv_img, cv2.COLOR_BGR2GRAY)
            
            # 2. Upscale image by 3x to improve DPI for Tesseract
            gray = cv2.resize(gray, None, fx=3, fy=3, interpolation=cv2.INTER_CUBIC)
            
            # 3. Apply Otsu's Binarization (Forces pixels to pure black or pure white)
            _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
            
            # Convert the processed OpenCV array back into a PIL Image for Tesseract
            img = Image.fromarray(thresh)
            
            ocr_text = pytesseract.image_to_string(img).strip()
        except Exception as e:
            print(f"OCR Error: {e}")
            ocr_text = f"[OCR Failed: {str(e)}]"

        # Create Document in DB
        document_record = Document(
            user_id=user_id,
            file_storage_url=file_path,
            raw_extracted_text=ocr_text
        )
        db.add(document_record)
        db.commit()

    # 3. Create Chat Messages
    # User message
    user_msg_content = message.strip()
    if ocr_text:
        user_msg_content += f"\n[Extracted Text from Image]: {ocr_text}"

    user_msg = ChatMessage(
        session_id=session.session_id,
        sender_role="User",
        message_content=user_msg_content
    )
    db.add(user_msg)

    # Mock AI message for now
    ai_msg = ChatMessage(
        session_id=session.session_id,
        sender_role="AI_Educator",
        message_content="I have received your message and processed the image!"
    )
    db.add(ai_msg)
    db.commit()

    # 4. Generate Embeddings & Store in Chroma DB
    text_to_embed = user_msg_content
    if text_to_embed:
        embeddings = embedder.encode(text_to_embed).tolist()
        
        chat_collection.add(
            embeddings=[embeddings],
            documents=[text_to_embed],
            metadatas=[{"user_id": user_id, "session_id": session.session_id, "role": "User"}],
            ids=[user_msg.message_id]
        )

    return {
        "status": "success",
        "message": "Message processed successfully",
        "ocr_text": ocr_text,
        "ai_response": ai_msg.message_content,
        "session_id": session.session_id
    }