# main.py
from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy import text
from sqlalchemy.orm import Session
from pydantic import BaseModel
import bcrypt
from jose import jwt
from datetime import datetime, timedelta
from typing import Optional

from database import get_db, engine
from models import User, ParametricProfile

# Run automatic schema migration for PostgreSQL
try:
    with engine.connect() as conn:
        conn.execute(text("ALTER TABLE parametric_profiles ADD COLUMN IF NOT EXISTS is_blind BOOLEAN DEFAULT FALSE;"))
        conn.commit()
    print("✅ PostgreSQL Schema Migration: 'is_blind' column verified/added")
except Exception as e:
    print(f"⚠️ PostgreSQL Schema Migration Failed: {e}")

app = FastAPI(title="ArthaSaathi API")

# --- Security Configuration ---
# --- Security Configuration ---
SECRET_KEY = "artha-saathi-super-secret-key"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_DAYS = 30

def get_password_hash(password: str):
    # bcrypt requires encoding strings into bytes before hashing
    salt = bcrypt.gensalt()
    hashed_bytes = bcrypt.hashpw(password.encode('utf-8'), salt)
    return hashed_bytes.decode('utf-8') # Decode back to string for Postgres

def verify_password(plain_password: str, hashed_password: str):
    return bcrypt.checkpw(plain_password.encode('utf-8'), hashed_password.encode('utf-8'))

def create_access_token(data: dict):
    to_encode = data.copy()
    expire = datetime.utcnow() + timedelta(days=ACCESS_TOKEN_EXPIRE_DAYS)
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)

# --- Pydantic Schema (Matches Frontend Payload) ---
class RegisterPayload(BaseModel):
    local_user_id: str
    local_profile_id: str
    phone_number: str
    password: str
    name: str
    language_code: str
    occupation_type: str
    education_level: str
    income_type: str
    income_value: str
    current_balance: float
    crop_type: Optional[str] = None
    land_holding: Optional[str] = None
    income_pattern: Optional[str] = None
    is_blind: bool = False

# --- Registration Endpoint ---
@app.post("/api/register")
def register_user(payload: RegisterPayload, db: Session = Depends(get_db)):
    # 1. Check if the phone number already exists in Postgres
    existing_user = db.query(User).filter(User.phone_number == payload.phone_number).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Phone number already registered")

    # 2. Hash the plaintext password sent from the phone
    hashed_pw = get_password_hash(payload.password)

    # 3. Save the User using the UUID generated by the frontend SQLite
    new_user = User(
        user_id=payload.local_user_id,
        phone_number=payload.phone_number,
        password_hash=hashed_pw
    )
    db.add(new_user)
    
    # 4. Save the Profile
    new_profile = ParametricProfile(
        profile_id=payload.local_profile_id,
        user_id=payload.local_user_id,
        name=payload.name,
        language_code=payload.language_code,
        occupation_type=payload.occupation_type,
        education_level=payload.education_level,
        income_type=payload.income_type,
        income_value=payload.income_value,
        current_balance=payload.current_balance,
        crop_type=payload.crop_type,
        land_holding=payload.land_holding,
        income_pattern=payload.income_pattern,
        is_blind=payload.is_blind
    )
    db.add(new_profile)
    db.commit()

    # 5. Generate and return the secure JWT
    access_token = create_access_token(data={"sub": new_user.user_id, "phone": new_user.phone_number})
    
    return {"access_token": access_token, "token_type": "bearer", "status": "success"}


@app.get("/api/profiles")
def get_all_profiles(db: Session = Depends(get_db)):
    # Fetch all profiles from the PostgreSQL database
    profiles = db.query(ParametricProfile).all()
    return profiles