# models.py
import uuid
from sqlalchemy import Column, String, Float, Integer, ForeignKey, DateTime, Boolean
from sqlalchemy.orm import relationship
from datetime import datetime
from database import Base, engine

class User(Base):
    __tablename__ = "users"
    
    # We use UUIDs so they match the offline IDs generated by React Native
    user_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    phone_number = Column(String, unique=True, index=True, nullable=False)
    password_hash = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    last_login = Column(DateTime, nullable=True)
    
    # Links the user to their profile
    profile = relationship("ParametricProfile", back_populates="user", uselist=False)
    # Links the user to their transactions
    transactions = relationship("Transaction", back_populates="user", cascade="all, delete-orphan")
    
    # Links to chat sessions and documents
    chat_sessions = relationship("ChatSession", back_populates="user")
    documents = relationship("Document", back_populates="user")

class ParametricProfile(Base):
    __tablename__ = "parametric_profiles"
    
    profile_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.user_id"), nullable=False)
    
    name = Column(String)
    language_code = Column(String)
    occupation_type = Column(String)
    education_level = Column(String)
    income_type = Column(String)
    income_value = Column(String)
    current_balance = Column(Float)
    
    # Nullable fields specifically for the Farmer persona
    crop_type = Column(String, nullable=True)
    land_holding = Column(String, nullable=True)
    income_pattern = Column(String, nullable=True)
    
    trust_score = Column(Integer, default=75)
    is_blind = Column(Boolean, default=False)

    # Links the profile back to the user
    user = relationship("User", back_populates="profile")

class Transaction(Base):
    __tablename__ = "transactions"
    
    transaction_id = Column(String, primary_key=True)
    user_id = Column(String, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False)
    amount = Column(Float, nullable=False)
    type = Column(String, nullable=False)  # 'credit' or 'debit'
    reason = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Links transaction back to user
    user = relationship("User", back_populates="transactions")
class Document(Base):
    __tablename__ = "documents"
    
    document_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.user_id"), nullable=False)
    file_storage_url = Column(String, nullable=False)
    document_type = Column(String, nullable=True)
    raw_extracted_text = Column(String, nullable=False)
    simplified_summary = Column(String, nullable=True)
    vector_collection_id = Column(String, nullable=True)
    upload_timestamp = Column(DateTime, default=datetime.utcnow)
    
    user = relationship("User", back_populates="documents")
    chat_sessions = relationship("ChatSession", back_populates="document")

class ChatSession(Base):
    __tablename__ = "chat_sessions"
    
    session_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.user_id"), nullable=False)
    document_id = Column(String, ForeignKey("documents.document_id"), nullable=True)
    session_title = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    user = relationship("User", back_populates="chat_sessions")
    document = relationship("Document", back_populates="chat_sessions")
    messages = relationship("ChatMessage", back_populates="session")

class ChatMessage(Base):
    __tablename__ = "chat_messages"
    
    message_id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String, ForeignKey("chat_sessions.session_id"), nullable=False)
    sender_role = Column(String, nullable=False)
    message_content = Column(String, nullable=False)
    guardrail_flagged = Column(Boolean, default=False)
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    session = relationship("ChatSession", back_populates="messages")

# This block actually creates the tables in Postgres when you run the file
if __name__ == "__main__":
    print("Creating database tables...")
    Base.metadata.create_all(bind=engine)
    print("Database tables created successfully!")